name: Fly Deploy Server
on:
  push:
    branches:
      - main
    paths:
      - 'packages/common/**'
      - 'packages/server/**'
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Image
      - run: sudo docker build . -f packages/server/Dockerfile -t ghcr.io/dragon-hatcher/ftc-scout-server:latest
      - name: Uploading
      - run: sudo docker push ghcr.io/dragon-hatcher/ftc-scout-server:latest
